#pragma once

namespace Engine
{
	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };
	enum LEVEL { LEVEL_STATIC, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_TOOL, LEVEL_LOADING, LEVEL_END };
}

enum CHANNELID {
	SOUND_BGM, SOUND_ENVIRONMENT,
	SOUND_PLAYER, SOUND_PLAYERFootStep,
	SOUND_Monster, SOUND_MonsterFootStep,
	SOUND_EFFECT, SOUND_EFFECT2,
	SOUND_UI,
	SOUND_SYSTEM_EFFECT, /* Bierce Announce */
	SOUND_SYSTEM_EFFECT2,
	MAXCHANNEL
};

enum CHANNEL_GROUP_ID { BGM_GROUP, SND1_GROUP, SND2_GROUP, MAX_CHANNEL_GROUP };