#pragma once

namespace Engine
{
	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum TextureType 
	{
		Type_NONE=0, Type_DIFFUSE, Type_SPECULAR, Type_AMBIENT, Type_EMISSIVE, Type_HEIGHT, Type_NORMALS
		, Type_SHININESS, Type_OPACITY, Type_DISPLACEMENT, Type_LIGHTMAP, Type_REFLECTION, Type_BASE_COLOR
		, Type_NORMAL_CAMERA, Type_EMISSION_COLOR, Type_METALNESS, Type_DIFFUSE_ROUGHNESS, Type_AMBIENT_OCCLUSION
		, Type_UNKNOWN
	};
}
enum MODEL_TYPE { NONANIM = 0, ANIM, NAVI, GROUND, TYPE_END };